#pragma once

enum BlockCut_t{
     BLOCK_CUT_WHOLE,
     BLOCK_CUT_LEFT_HALF,
     BLOCK_CUT_RIGHT_HALF,
     BLOCK_CUT_TOP_HALF,
     BLOCK_CUT_BOTTOM_HALF,
     BLOCK_CUT_TOP_LEFT_QUARTER,
     BLOCK_CUT_TOP_RIGHT_QUARTER,
     BLOCK_CUT_BOTTOM_LEFT_QUARTER,
     BLOCK_CUT_BOTTOM_RIGHT_QUARTER,
};

